### PR TITLE
Rename drop documentation for biography to content

### PR DESCRIPTION
**Pull request by JHarrison89**
The drop for biography was renamed to content. 
This commit renames the drop documentation file and references to content.

### CODE REVIEW

**Review by geoffreymm — COMMENTED** [review]
Nice one @JHarrison89 !

I think we just need to ensure we rename the reference too:
https://github.com/easolhq/easolhq.github.io/blob/main/docs/reference/objects/company.md#companybiographies

**Comment by JHarrison89** [comment]
> Nice one @JHarrison89 !
> 
> I think we just need to ensure we rename the reference too: https://github.com/easolhq/easolhq.github.io/blob/main/docs/reference/objects/company.md#companybiographies

**Review by geoffreymm — APPROVED** [review]
🎉 🎉 🎉 🎉

**Review by geoffreymm — APPROVED** [review]
Noticed now, for the extra shine, can we actually order the methods alphabetically? (Add add a `.` for each sentence too 🤓 )

**Pull request merged**
